# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - gripper_controller

  arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - Arm1_Joint
      - Arm2_Joint
      - Arm3_Joint
      - Arm4_Joint
      - Arm5_Joint
      # - vj1_joint
      # - vj2_joint

    open_loop_control: true
    allow_integration_in_goal_trajectories: true

  gripper_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - grip_joint

    open_loop_control: true
    allow_integration_in_goal_trajectories: true