# This config file is used by ros2_control

controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: false

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      publish_rate: 50.0
      use_local_clock: true   # ⭐ FIX → ensures real timestamps in /joint_states


arm_controller:
  ros__parameters:
    use_sim_time: false
    joints:
      - Arm1_Joint
      - Arm2_Joint
      - Arm3_Joint
      - Arm4_Joint
      - Arm5_Joint
    command_interfaces:
      - position
    state_interfaces:
      - position
    open_loop_control: true
    allow_integration_in_goal_trajectories: true


gripper_controller:
  ros__parameters:
    use_sim_time: false
    joints:
      - grip_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
